# Generated by Django 5.0.1 on 2024-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieproduit',
            name='intitule',
            field=models.CharField(max_length=50, unique=True, verbose_name='Intitulé de la catégorie de produit'),
        ),
        migrations.AlterField(
            model_name='typeproduit',
            name='intitule',
            field=models.CharField(max_length=50, unique=True, verbose_name='Intitulé du type de produit'),
        ),
    ]
