# Generated by Django 5.0.1 on 2024-08-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_commande_gerant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
    ]
