# Generated by Django 5.0.1 on 2024-08-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_customuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reapprovisionnement',
            name='gerant',
        ),
    ]
