# Generated by Django 5.0.1 on 2024-08-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(auto_now_add=True, verbose_name='date de commande'),
        ),
    ]
