# Generated by Django 5.0.1 on 2024-08-16 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reapprovisionnement',
            name='date_reapprovisionnement',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de réapprovisionnement'),
        ),
        migrations.AlterField(
            model_name='reapprovisionnement',
            name='prix_total',
            field=models.IntegerField(editable=False),
        ),
    ]
